### ISSUE TITLE
AGIC for Brownfield Deployments not Working

### ISSUE THREAD

**Issue by jocortems** [Azure/application-gateway-kubernetes-ingress#603]
**Describe the bug**
Trying to use an existing AppGW with VMs as backend pool and HTTPS listeners for exposing AKS services on both HTTP and HTTPS does not work, no changes are applied to the AppGW. The documentation used for the configuration was followed from here:

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-existing.md

From the Ingress Controller logs it appears we are running into a runtime error for invalid memory address or nil pointer deference. See logs below

**To Reproduce**
Follow the steps as indicated in this link:

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-existing.md

Using AAD Pod Identity

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

jorge@Azure:~/aks-agic$ kubectl describe pod good-zebu-ingress-azure-6d4df68c7d-6gvwk
Name:           good-zebu-ingress-azure-6d4df68c7d-6gvwk
Namespace:      default
Priority:       0
Node:           aks-nodepool1-12956168-vmss000001/10.0.0.35
Start Time:     Thu, 10 Oct 2019 02:52:19 +0000
Labels:         aadpodidbinding=good-zebu-ingress-azure
                app=ingress-azure
                pod-template-hash=6d4df68c7d
                release=good-zebu
Annotations:    <none>
Status:         Running
IP:             10.0.0.54
IPs:            <none>
Controlled By:  ReplicaSet/good-zebu-ingress-azure-6d4df68c7d
Containers:
  ingress-azure:
    Container ID:   docker://339d8fc18f20f0f3b6d207a5c2a85dfcbb260836de06fc14a6646d54d04038e9
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:ba9cb3968e02cbc61f313865c3bc7cbddf0d3e8a0e62bc1f502a67168e5e311c
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 10 Oct 2019 03:16:31 +0000
      Finished:     Thu, 10 Oct 2019 03:16:31 +0000
    Ready:          False
    Restart Count:  8
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      good-zebu-cm-ingress-azure  ConfigMap  Optional: false
    Environment:                  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from good-zebu-sa-ingress-azure-token-2cksl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  good-zebu-sa-ingress-azure-token-2cksl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  good-zebu-sa-ingress-azure-token-2cksl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                        Message
  ----     ------     ----                  ----                                        -------
  Normal   Scheduled  24m                   default-scheduler                           Successfully assigned default/good-zebu-ingress-azure-6d4df68c7d-6gvwk to aks-nodepool1-12956168-vmss000001
  Warning  Unhealthy  23m (x3 over 24m)     kubelet, aks-nodepool1-12956168-vmss000001  Liveness probe failed: Get http://10.0.0.54:8123/health/alive: dial tcp 10.0.0.54:8123: connect: connection refused
  Normal   Killing    23m                   kubelet, aks-nodepool1-12956168-vmss000001  Killing container with id docker://ingress-azure:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy  23m (x7 over 24m)     kubelet, aks-nodepool1-12956168-vmss000001  Readiness probe failed: Get http://10.0.0.54:8123/health/ready: dial tcp 10.0.0.54:8123: connect: connection refused
  Normal   Created    11m (x3 over 24m)     kubelet, aks-nodepool1-12956168-vmss000001  Created container
  Normal   Started    11m (x3 over 24m)     kubelet, aks-nodepool1-12956168-vmss000001  Started container
  Normal   Pulled     10m (x4 over 24m)     kubelet, aks-nodepool1-12956168-vmss000001  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0"
  Normal   Pulling    10m (x4 over 24m)     kubelet, aks-nodepool1-12956168-vmss000001  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0"
  Warning  BackOff    4m27s (x36 over 11m)  kubelet, aks-nodepool1-12956168-vmss000001  Back-off restarting failed container

* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.
jorge@Azure:~/aks-agic$ kubectl logs good-zebu-ingress-azure-6d4df68c7d-6gvwk
ERROR: logging before flag.Parse: I1010 03:16:31.316434       1 main.go:294] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I1010 03:16:31.316517       1 main.go:192] Creating authorizer from Azure Managed Service Identity
I1010 03:16:31.573475       1 main.go:117] Ingress Controller will observe all namespaces.
I1010 03:16:31.638626       1 context.go:122] k8s context run started
I1010 03:16:31.638661       1 context.go:161] Waiting for initial cache sync
E1010 03:16:31.691215       1 secretstore.go:70] secret [default/ca-secret] is not type kubernetes.io/tls
I1010 03:16:31.738902       1 context.go:169] Initial cache sync done
I1010 03:16:31.738932       1 context.go:170] k8s context run finished
I1010 03:16:31.739052       1 worker.go:33] Worker started
I1010 03:16:31.739219       1 main.go:140] Starting Health Probe Server on :8123
I1010 03:16:31.842761       1 process.go:65] [brownfield] Prohibited targets: {"Hostname":"vm.jorge4cortes.com"}, {"Hostname":"web.jorgecortes.ga"}, {"Hostname":"web.jorgecortes.gq"}, {"Hostname":"web.jorgecortes.cf"}, {"Hostname":"web.jorgecortes.ml"}
I1010 03:16:31.843116       1 health_probes.go:67] [brownfield] Probes AGIC created: defaultprobe-Http, defaultprobe-Https, pb-default-frontend-80-guestbook
I1010 03:16:31.843141       1 health_probes.go:68] [brownfield] Existing Blacklisted Probes AGIC will retain: vmhttps
I1010 03:16:31.843146       1 health_probes.go:69] [brownfield] Existing Probes AGIC will remove:
I1010 03:16:31.843283       1 http_settings.go:68] [brownfield] HTTP Settings AGIC created: defaulthttpsetting, bp-default-frontend-80-80-guestbook
I1010 03:16:31.843301       1 http_settings.go:69] [brownfield] Existing Blacklisted HTTP Settings AGIC will retain: vmhttpsroot
I1010 03:16:31.843305       1 http_settings.go:70] [brownfield] Existing HTTP Settings AGIC will remove:
I1010 03:16:31.843411       1 pools.go:67] [brownfield] Pools AGIC created: defaultaddresspool, pool-default-frontend-80-bp-80
I1010 03:16:31.843428       1 pools.go:68] [brownfield] Existing Blacklisted Pools AGIC will retain: VMBE
I1010 03:16:31.843432       1 pools.go:69] [brownfield] Existing Pools AGIC will remove: n/a
I1010 03:16:31.843587       1 listeners.go:82] [brownfield] Listeners AGIC created: fl-demo.jorge4cortes.com-80
I1010 03:16:31.843606       1 listeners.go:83] [brownfield] Existing Blacklisted Listeners AGIC will retain: cflistener, galistener, gqlistener, mllistener, CF-listener
I1010 03:16:31.843611       1 listeners.go:84] [brownfield] Existing Listeners AGIC will remove: n/a
I1010 03:16:31.843720       1 redirects.go:52] [brownfield] Redirects AGIC created: n/a
I1010 03:16:31.843736       1 redirects.go:53] [brownfield] Existing Blacklisted Redirects AGIC will retain: n/a
I1010 03:16:31.843740       1 redirects.go:54] [brownfield] Existing Redirects AGIC will remove: n/a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11f386d]

goroutine 147 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).groupListenersByListenerIdentifier(0xc00002ac60, 0xc00002a7e0, 0xc0007deb48)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/frontend_listeners.go:183 +0x32d
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).getRules(0xc00002ac60, 0xc00002a7e0, 0x0, 0x0, 0xc0007a8b40, 0x6, 0x8, 0x22ccc70)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:67 +0x6c
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).RequestRoutingRules(0xc00002ac60, 0xc00002a7e0, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:24 +0x8a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).Build(0xc00002ac60, 0xc00002a7e0, 0x0, 0x0, 0x24)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/configbuilder.go:99 +0x111
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.Process(0x16f5ac0, 0xc000267e70, 0x16f7240, 0xc0002a04e0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/process.go:115 +0xd44
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc000447b80, 0xc0000b8240, 0xc000090180)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:48 +0x2b7
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:65 +0x1bb

**Comment by jocortems** [comment]
I updated the image for the deployment created by the helm chart to 0.10.0-rc1 as suggested, the update was successful and the pod starts properly, however as soon as I deploy the ingress resource I am seeing the same error again. Cluster is running v1.13.10


jorge@Azure:~/aks-agic$ kubectl describe pod good-zebu-ingress-azure-66d8d7549c-4xglg
Name:           good-zebu-ingress-azure-66d8d7549c-4xglg
Namespace:      default
Priority:       0
Node:           aks-nodepool1-12956168-vmss000000/10.0.0.4
Start Time:     Fri, 11 Oct 2019 15:44:41 +0000
Labels:         aadpodidbinding=good-zebu-ingress-azure
                app=ingress-azure
                pod-template-hash=66d8d7549c
                release=good-zebu
Annotations:    <none>
Status:         Running
IP:             10.0.0.8
IPs:            <none>
Controlled By:  ReplicaSet/good-zebu-ingress-azure-66d8d7549c
Containers:
  ingress-azure:
    Container ID:   docker://146144be7b07e3c70bde26a8ebfd632b5d6be4a78f8bd57317267a2cfe318bf8
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.10.0-rc1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:874db4938c332920deea399a85d33bade264df240022123fc061b8f483e8c491
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 11 Oct 2019 15:44:57 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      good-zebu-cm-ingress-azure  ConfigMap  Optional: false
    Environment:                  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from good-zebu-sa-ingress-azure-token-2cksl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  good-zebu-sa-ingress-azure-token-2cksl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  good-zebu-sa-ingress-azure-token-2cksl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                        Message
  ----    ------     ----  ----                                        -------
  Normal  Scheduled  62s   default-scheduler                           Successfully assigned default/good-zebu-ingress-azure-66d8d7549c-4xglg to aks-nodepool1-12956168-vmss000000
  Normal  Pulling    61s   kubelet, aks-nodepool1-12956168-vmss000000  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.10.0-rc1"
  Normal  Pulled     54s   kubelet, aks-nodepool1-12956168-vmss000000  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.10.0-rc1"
  Normal  Created    46s   kubelet, aks-nodepool1-12956168-vmss000000  Created container
  Normal  Started    46s   kubelet, aks-nodepool1-12956168-vmss000000  Started container
jorge@Azure:~/aks-agic$ kubectl create -f https-ingress.yaml
ingress.extensions/guestbook created
jorge@Azure:~/aks-agic$ kubectl get pods
NAME                                       READY   STATUS    RESTARTS   AGE
frontend-74b4665db5-57bt5                  1/1     Running   0          37h
frontend-74b4665db5-c76mz                  1/1     Running   0          37h
frontend-74b4665db5-ftxrx                  1/1     Running   0          37h
good-zebu-ingress-azure-66d8d7549c-4xglg   0/1     Error     1          86s
mic-7dd7c656cb-gnvqs                       1/1     Running   0          37h
mic-7dd7c656cb-jx2vk                       1/1     Running   0          37h
nmi-fh74s                                  1/1     Running   0          37h
nmi-zjnkk                                  1/1     Running   0          37h
redis-master-6fbbc44567-stjmm              1/1     Running   0          37h
redis-slave-74ccb764fc-ngf4f               1/1     Running   0          37h
redis-slave-74ccb764fc-p7fvj               1/1     Running   0          37h
jorge@Azure:~/aks-agic$ kubectl logs good-zebu-ingress-azure-66d8d7549c-4xglg
ERROR: logging before flag.Parse: I1011 15:46:05.373107       1 main.go:256] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
E1011 15:46:05.375167       1 context.go:178] Error fetching AGIC Pod (This may happen if AGIC is running in a test environment), error occurred resource name may not be empty
I1011 15:46:05.375280       1 main.go:94] Unable to load Azure Context file:
I1011 15:46:05.375345       1 environment.go:137] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I1011 15:46:05.375367       1 main.go:113] App Gateway Details: Subscription: 75149352-2e54-4cad-ae5f-93718720f2e4, Resource Group: globant-rg, Name: sharedgw
I1011 15:46:05.375504       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I1011 15:46:05.897218       1 main.go:143] Ingress Controller will observe all namespaces.
I1011 15:46:05.993360       1 context.go:122] k8s context run started
I1011 15:46:05.993403       1 context.go:161] Waiting for initial cache sync
E1011 15:46:06.065358       1 secretstore.go:70] secret [default/ca-secret] is not type kubernetes.io/tls
I1011 15:46:06.094413       1 context.go:169] Initial cache sync done
I1011 15:46:06.094539       1 context.go:170] k8s context run finished
I1011 15:46:06.094707       1 httpserver.go:57] Starting API Server on :8123
I1011 15:46:06.094711       1 worker.go:33] Worker started
I1011 15:46:06.390260       1 process.go:61] [brownfield] Prohibited targets: {"Hostname":"vm.jorge4cortes.com"}, {"Hostname":"web.jorgecortes.ga"}, {"Hostname":"web.jorgecortes.gq"}, {"Hostname":"web.jorgecortes.cf"}, {"Hostname":"web.jorgecortes.ml"}
I1011 15:46:06.390687       1 health_probes.go:67] [brownfield] Probes AGIC created: pb-default-frontend-80-guestbook, defaultprobe-Http, defaultprobe-Https
I1011 15:46:06.390699       1 health_probes.go:68] [brownfield] Existing Blacklisted Probes AGIC will retain: vmhttps
I1011 15:46:06.390704       1 health_probes.go:69] [brownfield] Existing Probes AGIC will remove:
I1011 15:46:06.390872       1 http_settings.go:68] [brownfield] HTTP Settings AGIC created: defaulthttpsetting, bp-default-frontend-80-80-guestbook
I1011 15:46:06.390883       1 http_settings.go:69] [brownfield] Existing Blacklisted HTTP Settings AGIC will retain: vmhttpsroot
I1011 15:46:06.390893       1 http_settings.go:70] [brownfield] Existing HTTP Settings AGIC will remove:
I1011 15:46:06.391045       1 pools.go:67] [brownfield] Pools AGIC created: defaultaddresspool, pool-default-frontend-80-bp-80
I1011 15:46:06.391053       1 pools.go:68] [brownfield] Existing Blacklisted Pools AGIC will retain: VMBE
I1011 15:46:06.391058       1 pools.go:69] [brownfield] Existing Pools AGIC will remove: n/a
I1011 15:46:06.391199       1 listeners.go:82] [brownfield] Listeners AGIC created: fl-demo.jorge4cortes.com-80
I1011 15:46:06.391210       1 listeners.go:83] [brownfield] Existing Blacklisted Listeners AGIC will retain: cflistener, galistener, gqlistener, mllistener, CF-listener
I1011 15:46:06.391220       1 listeners.go:84] [brownfield] Existing Listeners AGIC will remove: n/a
I1011 15:46:06.391327       1 redirects.go:52] [brownfield] Redirects AGIC created: n/a
I1011 15:46:06.391333       1 redirects.go:53] [brownfield] Existing Blacklisted Redirects AGIC will retain: n/a
I1011 15:46:06.391337       1 redirects.go:54] [brownfield] Existing Redirects AGIC will remove: n/a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1249e7d]

goroutine 136 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).groupListenersByListenerIdentifier(0xc0008ab9e0, 0xc000103b80, 0xc000670f40)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/frontend_listeners.go:183 +0x32d
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).getRules(0xc0008ab9e0, 0xc000103b80, 0x0, 0x0, 0xc0001e6dc0, 0x6, 0x8, 0x2453ef8)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:67 +0x6c
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).RequestRoutingRules(0xc0008ab9e0, 0xc000103b80, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:24 +0x8a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).Build(0xc0008ab9e0, 0xc000103b80, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/configbuilder.go:99 +0x384
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.Process(0x1809140, 0xc000206dc0, 0xc000042056, 0x24, 0xc000044015, 0xa, 0xc00004408b, 0x8, 0xc0002af110, 0xc0003331f0, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/process.go:111 +0xc58
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0005bd790, 0xc00033f6e0, 0xc000090f00)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:48 +0x2b7
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:74 +0x1d2
jorge@Azure:~/aks-agic$

This is the YAML for the ingress resource I am creating. 

jorge@Azure:~/aks-agic$ cat https-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - hosts:
      - demo.jorge4cortes.com
      secretName: ca-secret
  rules:
  - host: demo.jorge4cortes.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
jorge@Azure:~/aks-agic$

**Comment by akshaysngupta** [comment]
This is partially fixed by https://github.com/Azure/application-gateway-kubernetes-ingress/pull/611

**Comment by draychev** [comment]
Hi @jocortems

Version `0.10.0-rc4` is out and in our Helm repo. This includes a fix for the nil pointer exception that you discovered - THANK you so much for helping troubleshoot and fix that!!

Here are the upgrade instructions: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade

Keep us posted on how well` 0.10.0-rc4` works with your setup!

I'll keep the issue open until you give us feedback on whether `0.10.0-rc4` addressed all issues you discovered!

**Comment by kylegalea** [comment]
We attempted the brownfield deployment today aswell - Version 0.10.0-rc4 and are having the same issue.

panic: runtime error: invalid memory address or nil pointer dereference

**Comment by draychev** [comment]
@kylegalea would you be so kind to post here a sanitized version of your `AzureIngressProhibitedTarget` and your `Ingress` resources / YAML?

**Comment by jocortems** [comment]
Hi @draychev I am testing with Version 0.10.0-rc4, I am hitting an invalid memory address or nil pointer dereference. However, this is different from the last time, in the previous version I would encounter this error only after deploying the ingress resource, with this version I am encountering this problem right off the bat after deploying the helm chart, don't even have a chance to deploy the Ingress resource:

jorge@Azure:~$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
funky-marmot    1               Fri Oct 25 17:37:31 2019        DEPLOYED        ingress-azure-0.10.0-rc4        0.10.0-rc4      default
jorge@Azure:~$ kubectl get ingress
No resources found in default namespace.
jorge@Azure:~$
jorge@Azure:~$ kubectl logs funky-marmot-ingress-azure-6897dddbdc-2lgwd
ERROR: logging before flag.Parse: I1025 19:08:16.547591       1 main.go:286] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I1025 19:08:16.595405       1 main.go:126] App Gateway Details: Subscription: 75149352-2e54-4cad-ae5f-93718720f2e4, Resource Group: kubetraining, Name: AKSVMAPPGW
I1025 19:08:16.595439       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I1025 19:08:16.798200       1 main.go:175] Ingress Controller will observe the following namespaces:default
I1025 19:08:16.826936       1 context.go:125] k8s context run started
I1025 19:08:16.827004       1 context.go:164] Waiting for initial cache sync
I1025 19:08:16.927232       1 context.go:172] Initial cache sync done
I1025 19:08:16.927258       1 context.go:173] k8s context run finished
I1025 19:08:16.927435       1 worker.go:33] Worker started
I1025 19:08:16.927527       1 httpserver.go:57] Starting API Server on :8123
I1025 19:08:17.059169       1 mutate_app_gateway.go:72] [brownfield] Prohibited targets: {"Path":"/*"}
I1025 19:08:17.059258       1 health_probes.go:67] [brownfield] Probes AGIC created: defaultprobe-Http, defaultprobe-Https
I1025 19:08:17.059269       1 health_probes.go:68] [brownfield] Existing Blacklisted Probes AGIC will retain: defaultprobe-Http
I1025 19:08:17.059273       1 health_probes.go:69] [brownfield] Existing Probes AGIC will remove:
I1025 19:08:17.059295       1 http_settings.go:68] [brownfield] HTTP Settings AGIC created: defaulthttpsetting
I1025 19:08:17.059300       1 http_settings.go:69] [brownfield] Existing Blacklisted HTTP Settings AGIC will retain: defaulthttpsetting
I1025 19:08:17.059304       1 http_settings.go:70] [brownfield] Existing HTTP Settings AGIC will remove: bp-default-frontend-80-80-frontend-ingress
I1025 19:08:17.059324       1 pools.go:67] [brownfield] Pools AGIC created: defaultaddresspool
I1025 19:08:17.059329       1 pools.go:68] [brownfield] Existing Blacklisted Pools AGIC will retain: autoscale-vmss
I1025 19:08:17.059333       1 pools.go:69] [brownfield] Existing Pools AGIC will remove: n/a
I1025 19:08:17.059400       1 listeners.go:82] [brownfield] Listeners AGIC created: fl-80
I1025 19:08:17.059407       1 listeners.go:83] [brownfield] Existing Blacklisted Listeners AGIC will retain: web-jorgecortes-gq
I1025 19:08:17.059411       1 listeners.go:84] [brownfield] Existing Listeners AGIC will remove: n/a
I1025 19:08:17.059443       1 ports.go:74] [brownfield] Ports AGIC created: fp-80
I1025 19:08:17.059448       1 ports.go:75] [brownfield] Existing Blacklisted Ports AGIC will retain: port_80
I1025 19:08:17.059452       1 ports.go:76] [brownfield] Existing Ports AGIC will remove: fp-443
I1025 19:08:17.059468       1 redirects.go:52] [brownfield] Redirects AGIC created: n/a
I1025 19:08:17.059472       1 redirects.go:53] [brownfield] Existing Blacklisted Redirects AGIC will retain: n/a
I1025 19:08:17.059476       1 redirects.go:54] [brownfield] Existing Redirects AGIC will remove: n/a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bfe7d]

goroutine 128 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).groupListenersByListenerIdentifier(0xc000886c60, 0xc000373380, 0xc0005751f8)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/frontend_listeners.go:190 +0x32d
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).getRules(0xc000886c60, 0xc000373380, 0x0, 0x0, 0xc0003f9e00, 0x2, 0x2, 0x24b4f38)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:67 +0x6c
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).RequestRoutingRules(0xc000886c60, 0xc000373380, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:24 +0x8a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).Build(0xc000886c60, 0xc000373380, 0x0, 0x0, 0x15)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/configbuilder.go:108 +0x384
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.MutateAppGateway(0x184a800, 0xc0001c0000, 0xc000042096, 0x24, 0xc000046015, 0xc, 0xc00004402b, 0xa, 0xc0004be660, 0xc00034ac00, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/mutate_app_gateway.go:125 +0xa2b
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc000551340, 0xc000356720, 0xc000360660)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:52 +0x34e
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:72 +0x1b5

**Comment by draychev** [comment]
@kylegalea @jocortems  we have a fix for the root cause of this https://github.com/Azure/application-gateway-kubernetes-ingress/pull/630
As soon as we are confident in the fix (when it is fully tested), it will be merged and I will let you know of a the new release of AGIC so you can upgrade - early next week!
Thanks for helping us troubleshoot this.

**Comment by draychev** [comment]
@kylegalea @jocortems  We just published a new release - https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.10.0-rc5 which addresses the issue you ran into.

Would you be so kind to `helm repo update` and upgrade to `0.10.0-rc5` ?
Detailed instructions on how to upgrade are [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade)

**Comment by jocortems** [comment]
@draychev Mi preliminary tests show this new release appears to be working fine with version 1.14.7; however, when deploying the helm chart for a cluster running preview 1.15.3 the controller pod keeps crashing and from the logs is stuck in the following error messages. Note this is before even deploying the ingress resource:

jorge@Azure:~/aks-agic$ kubectl logs bold-turkey-ingress-azure-75f4ffb9d8-f8r5w
ERROR: logging before flag.Parse: I1029 23:56:37.245504       1 main.go:286] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I1029 23:56:37.280464       1 environment.go:163] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I1029 23:56:37.280481       1 main.go:126] App Gateway Details: Subscription: 75149352-2e54-4cad-ae5f-93718720f2e4, Resource Group: kubetraining, Name: AKSVMAPPGW
I1029 23:56:37.280494       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
jorge@Azure:~/aks-agic$ kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
bold-turkey-ingress-azure-75f4ffb9d8-f8r5w   0/1     Running   3          3m11s
frontend-678d98b8f7-6sdmb                    1/1     Running   0          4d3h

**Comment by akshaysngupta** [comment]
I think this might be an issue with AAD Pod Identity. Let me follow through.

**Comment by nezoic** [comment]
I'm seeing the same issue here. Any updates on this?

**Comment by jocortems** [comment]
@nezoic It still doesn't work with AAD Pod Identity, but you can use service principal

**Comment by nezoic** [comment]
@jocortems Does this work for anyone with any configuration? I was using service principal but myself an other had issues with that, someone said it was only designed for testing / development but it doesn't even work for that from what I can tell. Sorry to sound rude but I've been trying to get this whole process working for over a month now and I'm going to be forced to throw up my own VM's and ditch AKS all together.

**Comment by jocortems** [comment]
@nezoic I tested this and works for me. I'm curious to understand what are the issues you are having

**Comment by niteenkole** [comment]
Works when I switch from AAD to SP ,I am using ingress-azure-1.0.0

**Comment by joelharkes** [comment]
@jocortems  i seem to get the same issues. it seems the helm template is missing role bindings for the ServiceAccount to actually access anything within k8s?

Should it work? without role bindings?

**Comment by joelharkes** [comment]
For those trying to make it work:

I setup a complete poewrshell script for all the steps of the brownfield installation with AA Pod identity.

i havent tested if all my powershell syntax works but might be usefull for you to trace your steps:

https://gist.github.com/joelharkes/e63482541abc5c3a396c5434549b8a58
