### ISSUE TITLE
SSL Redirection cannot be configured properly

### ISSUE THREAD

**Issue by rlevchenko** [Azure/application-gateway-kubernetes-ingress#914]
**Describe the bug**
My helm-managed ingress objects with url path-based routing, ssl offload and multiple hostnames features work fine, however, when I try to update them with ssl-redirect annotation the Ingress controller cannot properly apply a new configuration to application gateway. 

In that case, the controller only creates a HTTP listener and  a new rule (sslr-fl-09720eb9082cb7d02efdc60a169f3d35), see logs below) with a wrong type (Backend pool instead of the Redirection). As a result, such "configuration" opens a website on both 80 and 443 ports with no ssl-redirect configured. Have I missed any required configuration steps? Is it a bug?

**Steps to reproduce the behavior:**
Apply the ingress yaml files (below)

**Ingress Controller details**

Ingress version: 

1.2.0-rc1 , Kubernetes 1.16.9

Controller logs:

E0611 15:32:00.066922       1 requestroutingrules.go:258] Will not attach default redirect to rule; SSL Redirect does not exist: /subscriptions/xxxx/resourceGroups/cluster-k8s/providers/Microsoft.Network/applicationGateways/appgwf4f7/redirectConfigurations/sslr-fl-09720eb9082cb7d02efdc60a169f3d35

Ingress yaml (backend):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-api-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: appgw-ingress-tls
  rules:
    - host: www.contoso.com
      http:
        paths:
          - path: /path1/*
            backend:
              serviceName: gateway-api
              servicePort: 80
          - path: /path2*
            backend:
              serviceName: gateway-api
              servicePort: 80
```
Ingress yaml (frontend, providing only different parts):

```
http:
        paths:
          - backend:
              serviceName: myservice
              servicePort: 80
```

**Comment by StephanNel** [comment]
Experiencing the same problem, however I have no successful routing even on http. I get a SSL assigned when only using backend and no path. But when using the below nothing is created in APGW, this same does work on NGinX though.

`spec:
  tls:
    - hosts:
        - example.com
      secretName: example-secret
  rules:
    - host: example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: example-frontend-service
              servicePort: 80
          - path: /api/*
            backend:
              serviceName: example-backend-service
              servicePort: 80`

**Comment by akshaysngupta** [comment]
@rlevchenko / @StephanNel Do you see errors in your AGIC pod logs ? Also, can you make sure that the secret exists ?

**Comment by rlevchenko** [comment]
> @rlevchenko / @StephanNel Do you see errors in your AGIC pod logs ? Also, can you make sure that the secret exists ?

The secret exists. The AGIC works fine with disabled ssl redirection and enabled ssl offload = AGIC successfully uses the secret. There were only AGIC logs and they provided above. Tomorrow I'll try to enable ssl redirection to see whether AGIC produces any errors different than the one already mentioned.

**Comment by rlevchenko** [comment]
same error messages:

```
I0624 07:16:22.910002       1 mutate_app_gateway.go:167] BEGIN AppGateway deployment
I0624 07:17:35.250342       1 mutate_app_gateway.go:195] Applied App Gateway config in 1m12.340311919s
I0624 07:17:35.250371       1 mutate_app_gateway.go:214] cache: Updated with latest applied config.
I0624 07:17:35.254151       1 mutate_app_gateway.go:220] END AppGateway deployment
E0624 07:17:36.373465       1 requestroutingrules.go:258] Will not attach default redirect to rule; SSL Redirect does not exist: /subscriptions/xxxxx/resourceGroups/xxxcluster-k8s/providers/Microsoft.Network/applicationGateways/dlcappgwf4f7/redirectConfigurations/sslr-fl-09720eb9082cb7d02efdc60a169f3d35
E0624 07:17:36.373648       1 requestroutingrules.go:336] Will not attach redirect to rule; SSL Redirect does not exist: /subscriptions/xxxxxxxx/resourceGroups/xxxcluster-k8s/providers/Microsoft.Network/applicationGateways/dlcappgwf4f7/redirectConfigurations/sslr-fl-09720eb9082cb7d02efdc60a169f3d35
```

**Comment by mcarlsen** [comment]
FYI, this happened to us when we had the `aspnetapp` example app deployed. Its Ingress specifies no host name and we think this will cause conflict with any ssl redirection of host-based Ingresses.

We were surprised to see that the ingress controller opened up non-encrypted traffic for the host-based Ingresses.
Also, if this is caused by a configuration conflict as we think it was, it would be helpful if the error log indicated that there is such a conflict instead of "SSL Redirect does not exist".

**Comment by akshaysngupta** [comment]
@mcarlsen can you please share your redacted ingress.yamls?

**Comment by rlevchenko** [comment]
@mcarlsen thanks for sharing your exp, however, I don't use any HTTP applications at all. My apps are HTTPS and host-based with url path routing (some of them just use root path without additional paths though).  I will have a chance to test SSL redirection on a brand-new environment soon (will keep this thread updated)

**Comment by rlevchenko** [comment]
fixed long time ago by upgrading the appgw ingress

**Comment by jkroepke** [comment]
Hi @akshaysngupta 

we hitting this issue and just updating the ingress object (for example, add a randon not agic releated label) resolve this issue for us.

From my point of view, this issue is not resolved. It seems like an race-condition that AGIC is not going to create an SSL configuration and tries to use and existing one. After updating the ingress object, AGIC is going to create redirection configuration.

```
I0920 12:52:32.532535       1 context.go:712] IP 20.X.X.X already set on Ingress default/grafana
I0920 12:52:32.533711       1 backendhttpsettings.go:89] Created backend http settings bp-default-grafana-80-3000-grafana for ingress default/grafana and service default/grafana
E0920 12:52:32.533814       1 requestroutingrules.go:272] Will not attach default redirect to rule; SSL Redirect does not exist: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/redirectConfigurations/sslr-fl-3bfe32c3ed9c74095378fe96ec422c60
I0920 12:52:32.612673       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0920 12:52:33.239249       1 client.go:201] OperationID='f098bdf0-711a-48bd-8237-94c8d5d08242'
I0920 12:52:33.239277       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0920 12:52:33.239284       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0920 12:52:33.239947       1 mutate_app_gateway.go:204] END AppGateway deployment
I0920 12:52:33.239955       1 controller.go:151] Completed last event loop run in: 1.193118524s
I0920 12:59:56.731792       1 context.go:712] IP 20.X.X.X already set on Ingress default/grafana
I0920 12:59:56.737397       1 backendhttpsettings.go:89] Created backend http settings bp-default-grafana-80-3000-opsstack-grafana for ingress default/grafana and service default/grafana
I0920 12:59:56.737591       1 redirects.go:44] Created redirection configuration sslr-fl-3bfe32c3ed9c74095378fe96ec422c60 for ([grafana.company.cloud    ],443); not yet linked to a routing rule
I0920 12:59:56.767689       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0920 12:59:57.637591       1 client.go:201] OperationID='62e31f3a-1fe0-40e1-8099-084b27c62b4a'
I0920 13:00:48.213901       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0920 13:00:48.213966       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0920 13:00:48.215320       1 mutate_app_gateway.go:204] END AppGateway deployment
I0920 13:00:48.215339       1 controller.go:151] Completed last event loop run in: 51.721836944s
```

Please mention that restarting the AGIC pod wont help here.
